// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.0--rc3
// source: products.proto

package products_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReq) Reset() {
	*x = CreateProductReq{}
	mi := &file_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReq) ProtoMessage() {}

func (x *CreateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReq.ProtoReflect.Descriptor instead.
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateProductRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRes) Reset() {
	*x = CreateProductRes{}
	mi := &file_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRes) ProtoMessage() {}

func (x *CreateProductRes) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRes.ProtoReflect.Descriptor instead.
func (*CreateProductRes) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductRes) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type UpdateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReq) Reset() {
	*x = UpdateProductReq{}
	mi := &file_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReq) ProtoMessage() {}

func (x *UpdateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReq.ProtoReflect.Descriptor instead.
func (*UpdateProductReq) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProductReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateProductRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRes) Reset() {
	*x = UpdateProductRes{}
	mi := &file_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRes) ProtoMessage() {}

func (x *UpdateProductRes) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRes.ProtoReflect.Descriptor instead.
func (*UpdateProductRes) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{4}
}

type GetProductByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIdReq) Reset() {
	*x = GetProductByIdReq{}
	mi := &file_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIdReq) ProtoMessage() {}

func (x *GetProductByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIdReq.ProtoReflect.Descriptor instead.
func (*GetProductByIdReq) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductByIdReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetProductByIdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=Product,proto3" json:"Product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIdRes) Reset() {
	*x = GetProductByIdRes{}
	mi := &file_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIdRes) ProtoMessage() {}

func (x *GetProductByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIdRes.ProtoReflect.Descriptor instead.
func (*GetProductByIdRes) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductByIdRes) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_products_proto protoreflect.FileDescriptor

const file_products_proto_rawDesc = "" +
	"\n" +
	"\x0eproducts.proto\x12\x10products_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x01\n" +
	"\aProduct\x12\x1c\n" +
	"\tProductId\x18\x01 \x01(\tR\tProductId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x14\n" +
	"\x05Price\x18\x04 \x01(\x01R\x05Price\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\"^\n" +
	"\x10CreateProductReq\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\x01R\x05Price\"0\n" +
	"\x10CreateProductRes\x12\x1c\n" +
	"\tProductId\x18\x01 \x01(\tR\tProductId\"|\n" +
	"\x10UpdateProductReq\x12\x1c\n" +
	"\tProductId\x18\x01 \x01(\tR\tProductId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x14\n" +
	"\x05Price\x18\x04 \x01(\x01R\x05Price\"\x12\n" +
	"\x10UpdateProductRes\"1\n" +
	"\x11GetProductByIdReq\x12\x1c\n" +
	"\tProductId\x18\x01 \x01(\tR\tProductId\"H\n" +
	"\x11GetProductByIdRes\x123\n" +
	"\aProduct\x18\x01 \x01(\v2\x19.products_service.ProductR\aProduct2\x9f\x02\n" +
	"\x0fProductsService\x12W\n" +
	"\rCreateProduct\x12\".products_service.CreateProductReq\x1a\".products_service.CreateProductRes\x12W\n" +
	"\rUpdateProduct\x12\".products_service.UpdateProductReq\x1a\".products_service.UpdateProductRes\x12Z\n" +
	"\x0eGetProductById\x12#.products_service.GetProductByIdReq\x1a#.products_service.GetProductByIdResB\x15Z\x13./;products_serviceb\x06proto3"

var (
	file_products_proto_rawDescOnce sync.Once
	file_products_proto_rawDescData []byte
)

func file_products_proto_rawDescGZIP() []byte {
	file_products_proto_rawDescOnce.Do(func() {
		file_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_proto_rawDesc), len(file_products_proto_rawDesc)))
	})
	return file_products_proto_rawDescData
}

var file_products_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_products_proto_goTypes = []any{
	(*Product)(nil),               // 0: products_service.Product
	(*CreateProductReq)(nil),      // 1: products_service.CreateProductReq
	(*CreateProductRes)(nil),      // 2: products_service.CreateProductRes
	(*UpdateProductReq)(nil),      // 3: products_service.UpdateProductReq
	(*UpdateProductRes)(nil),      // 4: products_service.UpdateProductRes
	(*GetProductByIdReq)(nil),     // 5: products_service.GetProductByIdReq
	(*GetProductByIdRes)(nil),     // 6: products_service.GetProductByIdRes
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_products_proto_depIdxs = []int32{
	7, // 0: products_service.Product.CreatedAt:type_name -> google.protobuf.Timestamp
	7, // 1: products_service.Product.UpdatedAt:type_name -> google.protobuf.Timestamp
	0, // 2: products_service.GetProductByIdRes.Product:type_name -> products_service.Product
	1, // 3: products_service.ProductsService.CreateProduct:input_type -> products_service.CreateProductReq
	3, // 4: products_service.ProductsService.UpdateProduct:input_type -> products_service.UpdateProductReq
	5, // 5: products_service.ProductsService.GetProductById:input_type -> products_service.GetProductByIdReq
	2, // 6: products_service.ProductsService.CreateProduct:output_type -> products_service.CreateProductRes
	4, // 7: products_service.ProductsService.UpdateProduct:output_type -> products_service.UpdateProductRes
	6, // 8: products_service.ProductsService.GetProductById:output_type -> products_service.GetProductByIdRes
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_products_proto_init() }
func file_products_proto_init() {
	if File_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_proto_rawDesc), len(file_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_proto_goTypes,
		DependencyIndexes: file_products_proto_depIdxs,
		MessageInfos:      file_products_proto_msgTypes,
	}.Build()
	File_products_proto = out.File
	file_products_proto_goTypes = nil
	file_products_proto_depIdxs = nil
}
